### ISSUE TITLE
在本地启动的server, mock链接无法访问

### ISSUE THREAD

**Issue by dlutwuwei** [YMFE/yapi#101]
## Version
 
"version": "1.3.1",

## What is expected

mock链接可以访问

## Step to reproduce
看代码，是
```
        let ip = context.ctx.ip.match(/\d+.\d+.\d+.\d+/)[0];

```
所有的context都没有ip这个字段

```
error: TypeError: Cannot read property '0' of null
    at checkCase (/Users/wuwei/my-yapi/vendors/exts/yapi-plugin-advanced-mock/server.js:44:45)
    at Object.<anonymous> (/Users/wuwei/my-yapi/vendors/exts/yapi-plugin-advanced-mock/server.js:158:26)
    at Object.emitHook (/Users/wuwei/my-yapi/vendors/server/plugin.js:191:65)
    at module.exports (/Users/wuwei/my-yapi/vendors/server/middleware/mockServer.js:205:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Environment

mongodb 2.6 node 8.9 / mac os

**Comment by gaoxiaomumu** [comment]
您好，该问题已经解决，会在下一个版本中发布。您可以用其他的域名来代替localhost  或者直接用127.0.0.1

**Comment by gaoxiaomumu** [comment]
您好，该问题已经解决，会在下一个版本中发布。您可以用其他的域名来代替localhost  或者直接用127.0.0.1
