### ISSUE TITLE
从1.5.11升级到1.5.14后启动报错

### ISSUE THREAD

**Issue by TianTian106** [YMFE/yapi#1010]
## 版本号
~ 1.5.14
## node版本换了以下两个都报同样的错误。
node-v7.6.0
node-v8.0.0

## 什么问题
~从1.5.11升级到1.5.14后，启动node app.js后报错如下：
/app/yapi/vendors/common/postmanLib.js:250
    ...commonContext,
    ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/yapi/vendors/server/controllers/open.js:15:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

## 如何复现此问题
~ 

## 什么浏览器
~ chrom

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by hellosean1025** [comment]
node请升级到 8.9

**Comment by TianTian106** [comment]
已解决，非常感谢~

**Comment by TianTian106** [comment]
已解决，非常感谢~
