### ISSUE TITLE
导出swagger json 报错

### ISSUE THREAD

**Issue by tanlzhi** [YMFE/yapi#1063]
## 版本号
1.7.0

## 什么问题
导出swagger json格式失败

## 如何复现此问题
数据管理--》数据导出--》选择swagger json

{
errcode: 502,
errmsg: "下载出错",
data: null
}

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by tanlzhi** [comment]
补充错误日志：
error: SyntaxError: Unexpected token / in JSON at position 49
    at JSON.parse (<anonymous>)
    at swaggerObj.paths.apisObj.(anonymous function).(anonymous function).apiItem.parameters (/Users/tanlongzhi/yapi/vendors/exts/yapi-plugin-export-swagger2-data/controller.js:213:74)
    at swaggerObj.paths.apisObj.(anonymous function).(anonymous function) (/Users/tanlongzhi/yapi/vendors/exts/yapi-plugin-export-swagger2-data/controller.js:253:35)
    at swaggerObj.paths (/Users/tanlongzhi/yapi/vendors/exts/yapi-plugin-export-swagger2-data/controller.js:277:31)
    at convertToSwaggerV2Model (/Users/tanlongzhi/yapi/vendors/exts/yapi-plugin-export-swagger2-data/controller.js:281:19)
    at exportSwaggerController.exportData (/Users/tanlongzhi/yapi/vendors/exts/yapi-plugin-export-swagger2-data/controller.js:88:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by johnfwtest** [comment]
初步看起来像是接口设置的传入参数类型为Json，但参数的格式却不能序列化为json导致的。
接口是从其他系统导入的吗？
你可以导出json格式（非swagger json），然后排查一下属性为req_body_type为json的api中req_body_other属性有没有不能被json序列化的

**Comment by johnfwtest** [comment]
尤其是有字符  /  的api项

**Comment by tanlzhi** [comment]
> 初步看起来像是接口设置的传入参数类型为Json，但参数的格式却不能序列化为json导致的。
> 接口是从其他系统导入的吗？
> 你可以导出json格式（非swagger json），然后排查一下req_body_type属性为json的api中req_body_other属性的值有没有不能被json序列化的

谢谢提醒！问题找到了，如果通过json5->使用注释方式写参数说明 ,这种情况下不能导出swagger，必须通过json-schema定义每个参数类型。

**Comment by coopercoder** [comment]
> > 初步看起来像是接口设置的传入参数类型为Json，但参数的格式却不能序列化为json导致的。
> > 接口是从其他系统导入的吗？
> > 你可以导出json格式（非swagger json），然后排查一下req_body_type属性为json的api中req_body_other属性的值有没有不能被json序列化的
> 
> 谢谢提醒！问题找到了，如果通过json5->使用注释方式写参数说明 ,这种情况下不能导出swagger，必须通过json-schema定义每个参数类型。

是的，确实是因为json5导致的，有什么办法让json5的也能导出swagger吗

**Comment by iceprosurface** [comment]
@coopercoder 
我觉得这个是不是直接用 json5 是不是就好了
https://github.com/YMFE/yapi/blob/8e1f6546d52ad6a3f8d3ce3325eb1d0276209f4c/exts/yapi-plugin-export-swagger2-data/controller.js#L89
