### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by 891809266** [YMFE/yapi#1120]
## 版本号
~ 
所有版本
## 什么问题
~
当前安装版本： 1.7.0
C:\Users\89180\AppData\Roaming\npm\node_modules\yapi-cli\node_modules\mongodb-core\lib\connection\commands.js:446
  this.documents = new Array(this.numberReturned);
                   ^

RangeError: Invalid array length
    at new Response (C:\Users\89180\AppData\Roaming\npm\node_modules\yapi-cli\node_modules\mongodb-core\lib\connection\commands.js:446:20)
    at Socket.<anonymous> (C:\Users\89180\AppData\Roaming\npm\node_modules\yapi-cli\node_modules\mongodb-core\lib\connection\connection.js:363:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
## 如何复现此问题
~ 
npm install -g yapi-cli
yapi server
## 什么浏览器
~ 
chrome
## 什么系统（Linux, Windows, macOS）
windows, centos7

**Comment by chobits4** [comment]
![image](https://user-images.githubusercontent.com/33352251/58925694-03716100-877b-11e9-8cd3-5ea6345735b6.png)

**Comment by gongzh021** [comment]
同样的问题 , 你解决了吗

**Comment by tmlx1990** [comment]
nodejs版本是什么？试试16的

**Comment by gongzh021** [comment]
> nodejs版本是什么？试试16的

v8.17.0
