### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by lengrongfu** [YMFE/yapi#143]
/usr/lib/node_modules/yapi-cli/src/commands/install.js:38
async function verifyConfig(config){
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/yapi-cli/src/index.js:10:23

**Comment by roscoe054** [comment]
检查一下 Node.js 版本？需要 >= 7.6.0
