### ISSUE TITLE
npm run install-server 失败

### ISSUE THREAD

**Issue by tan-hui** [YMFE/yapi#1454]
## 版本号
~ 

## 什么问题
>  node server/install.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../config.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/yapi/vendors/server/yapi.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yapi-vendor@1.8.5 install-server: ` node server/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yapi-vendor@1.8.5 install-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-29T17_04_09_215Z-debug.log

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
linux

**Comment by tangcent** [comment]
- 实际上你可以很容易通过issue的搜索功能找到相关信息:
[issues search result](https://github.com/YMFE/yapi/issues?utf8=%E2%9C%93&q=Cannot+find+module+%27..%2F..%2Fconfig.json%27)
- see https://github.com/YMFE/yapi/issues/1431#issuecomment-544776880
- see [redev.html](https://hellosean1025.github.io/yapi/documents/redev.html)
