### ISSUE TITLE
启动时报错信息/usr/lib/node_modules/yapi-cli/src/utils.js:68

### ISSUE THREAD

**Issue by lgl48128244** [YMFE/yapi#1569]
## 版本号
~ 

## 什么问题
~启动时报错信息

[root@lokbird ~]# yapi-cli server
/usr/lib/node_modules/yapi-cli/src/utils.js:68
  getVersions: async function(){
                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/yapi-cli/src/index.js:4:15)
[root@lokbird ~]# 

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
centos7

**Comment by KeJemas** [comment]
同问，解决了吗

**Comment by Ha2ryZhang** [comment]
+1

**Comment by Humengchao** [comment]
+1
