### ISSUE TITLE
启动后连接数暴增 是什么情况？

### ISSUE THREAD

**Issue by fengyingkong** [YMFE/yapi#1669]
## 版本号
~ 1.8.9

## 什么问题
~ Cannot assign requested address
连接mongodb报错，dba查看是说yapi不知道为什么启动后会暴增连接数。

## 如何复现此问题
~ 设置mongodb连接100，启动项目后会跑错误

## 什么浏览器
~ 谷歌

## 什么系统（Linux, Windows, macOS）
linux

**Comment by fengyingkong** [comment]
连接数暴增到700+
日志报错：
log: mongodb load success...
{ MongoError: Cannot assign requested address
    at Connection.<anonymous> (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:466:61)
    at Connection.emit (events.js:198:13)
    at processMessage (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:364:10)
    at Socket.<anonymous> (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:533:15)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_st
