### ISSUE TITLE
高级Mock添加期望报错

### ISSUE THREAD

**Issue by shellwalker** [YMFE/yapi#168]
## 版本号
~ 1.3.6

## 什么问题
~ 高级Mock添加期望报错

  errors: 
   { res_body: 
      { CastError: Cast to String failed for value "{ text: '[\n  {"name": "123"},\n  {"test":"asdf"}\n]',
  format: true,
  jsonData: [ { name: '123' }, { test: 'asdf' } ] }" at path "res_body"
    at new CastError (/home/my-yapi/vendors/node_modules/mongoose/lib/error/cast.js:26:11)
    at model.Document.set (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:741:7)
    at model._handleIndex (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:583:14)
    at model.Document.set (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:544:24)
    at model.Document (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:68:10)
    at model.Model (/home/my-yapi/vendors/node_modules/mongoose/lib/model.js:48:12)
    at new model (/home/my-yapi/vendors/node_modules/mongoose/lib/model.js:3229:13)
    at caseModel.save (/home/my-yapi/vendors/exts/yapi-plugin-advanced-mock/caseModel.js:54:13)
    at advMockController.saveCase (/home/my-yapi/vendors/exts/yapi-plugin-advanced-mock/controller.js:145:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
        message: 'Cast to String failed for value "{ text: \'[\\n  {"name": "123"},\\n  {"test":"asdf"}\\n]\',\n  format: true,\n  jsonData: [ { name: \'123\' }, { test: \'asdf\' } ] }" at path "res_body"',
        name: 'CastError',
        kind: 'String',
        value: [Object],
        path: 'res_body',
        reason: [Object] } },
  message: 'adv_mock_case validation failed',
  name: 'ValidationError' }

## 如何复现此问题
~ 1. 任意添加一普通mock
    2. 进入高级mock，添加期望
    3. 改动响应中的body内容

## 什么浏览器
~ chrome   版本 64.0.3282.168（正式版本） （64 位）

## 什么系统（linux, window, macox）
服务端：Ubuntu 16.04（阿里云）
客户端：Windows 10

**Comment by suxiaoxin** [comment]
发现你添加的内容

**Comment by shellwalker** [comment]
![1-- mock](https://user-images.githubusercontent.com/23768098/36720162-2a913432-1be2-11e8-8dd7-c7a434636835.jpg)
![2-- mock](https://user-images.githubusercontent.com/23768098/36720159-29a37da0-1be2-11e8-823c-b91172a2d7f6.jpg)


```
{
  "name": "xiugai"
}
```

**错误提示如下：**
  errors: 
   { res_body: 
      { CastError: Cast to String failed for value "{ text: '{\n  "name": "xiugai"\n}',
  format: true,
  jsonData: { name: 'xiugai' } }" at path "res_body"
    at new CastError (/home/my-yapi/vendors/node_modules/mongoose/lib/error/cast.js:26:11)
    at model.Document.set (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:741:7)
    at model._handleIndex (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:583:14)
    at model.Document.set (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:544:24)
    at model.Document (/home/my-yapi/vendors/node_modules/mongoose/lib/document.js:68:10)
    at model.Model (/home/my-yapi/vendors/node_modules/mongoose/lib/model.js:48:12)
    at new model (/home/my-yapi/vendors/node_modules/mongoose/lib/model.js:3229:13)
    at caseModel.save (/home/my-yapi/vendors/exts/yapi-plugin-advanced-mock/caseModel.js:54:13)
    at advMockController.saveCase (/home/my-yapi/vendors/exts/yapi-plugin-advanced-mock/controller.js:145:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
        message: 'Cast to String failed for value "{ text: \'{\\n  "name": "xiugai"\\n}\',\n  format: true,\n  jsonData: { name: \'xiugai\' } }" at path "res_body"',
        name: 'CastError',
        kind: 'String',
        value: [Object],
        path: 'res_body',
        reason: [Object] } },
  message: 'adv_mock_case validation failed',
  name: 'ValidationError' }

**Comment by suxiaoxin** [comment]
Fix in the v1.3.7,下周发新版，请关注官网的更新。
