### ISSUE TITLE
查看系统信息 时候 报错

### ISSUE THREAD

**Issue by yili1992** [YMFE/yapi#172]
## 版本号
~ 1.3.6

## 什么问题
`
(node:15279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: { MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/connection.js:309:22)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
  name: 'MongoError',
  message: 'The \'cursor\' option is required, except for aggregate with the explain argument',
  ok: 0,
  errmsg: 'The \'cursor\' option is required, except for aggregate with the explain argument',
  code: 9,
  codeName: 'FailedToParse' }
(node:15279) UnhandledPromiseRejectionWarning: MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/Users/zhaoli/Documents/B.03Code_Space/NodeJs_workspace/yapi/my-yapi/vendors/node_modules/mongodb-core/lib/connection/connection.js:309:22)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
(node:15279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`

## 如何复现此问题
~ 

## 什么浏览器
~ Chrome

## 什么系统（linux, window, macox）
macos

**Comment by suxiaoxin** [comment]
无法复现

**Comment by yili1992** [comment]
类似问题https://github.com/Mockgoose/Mockgoose/issues/32，   我的 mongodb  3.6.2  后来把"mongoose" 升到 "4.13.7" 版本就好了
