### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by ethanfly** [YMFE/yapi#1736]
## 版本号
~ 

## 什么问题
~
![image](https://user-images.githubusercontent.com/22938693/80678474-874bde80-8aed-11ea-9886-9a19d9942ec7.png)

## 如何复现此问题
~ 
运行安装程序时出现

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
centos 8.1

**Comment by ethanfly** [comment]
Error:  (node:4273) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by epoll-j** [comment]
同样的问题

**Comment by epoll-j** [comment]
```
gyp WARN install got an error, rolling back install

 gyp

 ERR! configure error
gyp
 ERR! stack Error: Client network socket disconnected before secure TLS connection was established
gyp ERR! stack     at connResetException (internal/errors.js:613:14)
gyp
  ERR! stack     at TLSSocket.onConnectEnd (_tls_wrap.js:1525:19)
gyp ERR! stack     at TLSSocket.emit (events.js:327:22)
gyp
  ERR! stack     at endReadableNT (_stream_readable.js:1218:12)
gyp
  ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)

 gyp
  ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /my-yapi/vendors/node_modules/dtrace-provider
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v
  v5.1.0
gyp
 ERR! not ok


> core-js@2.6.11 postinstall /my-yapi/vendors/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


 npm
  WARN
  mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.3.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN
  react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.

 npm
 WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.


 added 335 packages from 332 contributors in 164.631s


3 packages are looking for funding
  run `npm fund` for details


依赖库安装完成，正在初始化数据库mongodb...

> yapi-vendor@1.9.1 install-server /my-yapi/vendors
>  node server/install.js


Error:  (node:110) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by zhangbojr** [comment]
我也遇到同样的问题

**Comment by biuboompa** [comment]
真的垃圾 我搞了一晚上还是这样 这个作者能不能有点心

**Comment by mysunnyshine** [comment]
我也遇到了同样的问题，请问你怎么解决的

**Comment by wx85745997** [comment]
(node:26295) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26295) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:26295) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

node v14.5.0
降级v12.18.2  报错消失

**Comment by AlexWuYh** [comment]
> (node:26295) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:26295) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
> (node:26295) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
> 
> node v14.5.0
> 降级v12.18.2 报错消失

遇到同样的问题，把node从14.x降级到12.x后解决了👍👍👍

**Comment by daxiaraoming** [comment]
same problem here v14.14.0

**Comment by gh316** [comment]
你们咋解决的

**Comment by AlexWuYh** [comment]
> 你们咋解决的

降级node版本到12.x

**Comment by gh316** [comment]
> > 你们咋解决的
> 
> 降级node版本到12.x

好吧，正在折腾
