### ISSUE TITLE
yapi server命令 启动报错  在线等急急急！！！！

### ISSUE THREAD

**Issue by fxzzq** [YMFE/yapi#1765]
## 版本号
~ 1.5
node   mongdb  git 都装了

## 什么问题
~yapi server命令 启动报错
internal/modules/cjs/loader.js:583 throw err; ^ Error: Cannot find module 'D:\Program' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15) at Function.Module._load (internal/modules/cjs/loader.js:507:25) at Function.Module.runMain (internal/modules/cjs/loader.js:742:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
## 如何复现此问题
~ Ubuntu下装很顺利
回家windows 遇到问题 也顺利安装了 ，就是公司这个windows很诡异。
## 什么浏览器
~ 
Google
## 什么系统（Linux, Windows, macOS）
windows

**Comment by lifw555** [comment]
别放到有空格的目录下，那个会产生诡异问题。

**Comment by xhxhxhxh** [comment]
c\user 目录下的用户名有空格、
npm install yapi-cli --registry https://registry.npm.taobao.org
npx yapi server
解决！
