### ISSUE TITLE
 No ESLint configuration found 

### ISSUE THREAD

**Issue by fivge** [YMFE/yapi#1776]
## 版本号

~ 1.9.1

## 什么问题

~ 二次开发构建时报错

## 什么系统（Linux, Windows, macOS）

openSUSE 15.1

```bash
$ /home/x/yApi/vendors/node_modules/.bin/ykit pack -l false -m
[error] ./client/index.js
Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/home/x/yApi/vendors/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/home/x/yApi/vendors/node_modules/eslint/lib/config.js:260:26)
    at processText (/home/x/yApi/vendors/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/home/x/yApi/vendors/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/home/x/yApi/vendors/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/x/yApi/vendors/node_modules/eslint-loader/index.js:213:21)
 @ multi index.js

error Command failed with exit code 1.
```

**Comment by aqiu202** [comment]
ykit.config.js中注释以下代码即可
![image](https://user-images.githubusercontent.com/24487480/83395033-2b49e200-a42c-11ea-9181-b776ab5a1671.png)
