### ISSUE TITLE
集成yapi-plugin-ww-login 报错

### ISSUE THREAD

**Issue by dybxin** [YMFE/yapi#1799]
## 版本号
~ 拉取的最新代码

## 什么问题
[root@iZj6cc4w2ham1fp939fxllZ vendors]# npm run install-server

> yapi-vendor@1.9.1 install-server /root/yapi/vendors
>  node server/install.js

log: mongodb load success...
初始化管理员账号成功,账号名："admin@admin.com"，密码："ymfe.org"
[root@iZj6cc4w2ham1fp939fxllZ vendors]# node server/app.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yapi-plugin-ww-login'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getPluginConfig (/root/yapi/vendors/common/plugin.js:8:20)
    at plugins.map.item (/root/yapi/vendors/common/plugin.js:39:22)
    at Array.map (<anonymous>)
    at exports.initPlugins (/root/yapi/vendors/common/plugin.js:33:21)
    at Object.<anonymous> (/root/yapi/vendors/server/plugin.js:235:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)

## 如何复现此问题
~ 修改config.json
{
  "port": "3000",
  "adminAccount": "admin@admin.com",
  "timeout":120000,
  "db": {
    "servername": "127.0.0.1",
    "DATABASE": "yapi",
    "port": 27017,
    "user": "test1",
    "pass": "test1",
    "authSource": ""
  },
  "mail": {
    "enable": true,
    "host": "smtp.163.com",
    "port": 465,
    "from": "***@163.com",
    "auth": {
      "user": "***@163.com",
      "pass": "*****"
    }
  },
  "plugins": [
    {
      "name": "ww-login",
      "options": {
        "appid": "xxxxxx",
        "agentid": "xxxxxx",
        "secret": "xxxxxx",
        "redirectUri":"http://xxxxxxxx/api/plugin/wx/login"
      }
    }
  ]
}

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
linux

**Comment by dybxin** [comment]
> ## 版本号
> ~ 拉取的最新代码
> 
> ## 什么问题
> [root@iZj6cc4w2ham1fp939fxllZ vendors]# npm run install-server
> 
> > yapi-vendor@1.9.1 install-server /root/yapi/vendors
> > node server/install.js
> 
> log: mongodb load success...
> 初始化管理员账号成功,账号名："[admin@admin.com](mailto:admin@admin.com)"，密码："ymfe.org"
> [root@iZj6cc4w2ham1fp939fxllZ vendors]# node server/app.js
> internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> Error: Cannot find module 'yapi-plugin-ww-login'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Module.require (internal/modules/cjs/loader.js:690:17)
> at require (internal/modules/cjs/helpers.js:25:18)
> at getPluginConfig (/root/yapi/vendors/common/plugin.js:8:20)
> at plugins.map.item (/root/yapi/vendors/common/plugin.js:39:22)
> at Array.map ()
> at exports.initPlugins (/root/yapi/vendors/common/plugin.js:33:21)
> at Object. (/root/yapi/vendors/server/plugin.js:235:21)
> at Module._compile (internal/modules/cjs/loader.js:776:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Module.require (internal/modules/cjs/loader.js:690:17)
> at require (internal/modules/cjs/helpers.js:25:18)
> 
> ## 如何复现此问题
> ~ 修改config.json
> {
> "port": "3000",
> "adminAccount": "[admin@admin.com](mailto:admin@admin.com)",
> "timeout":120000,
> "db": {
> "servername": "127.0.0.1",
> "DATABASE": "yapi",
> "port": 27017,
> "user": "test1",
> "pass": "test1",
> "authSource": ""
> },
> "mail": {
> "enable": true,
> "host": "smtp.163.com",
> "port": 465,
> "from": "_**@163.com", "auth": { "user": "**_@163.com",
> "pass": "*****"
> }
> },
> "plugins": [
> {
> "name": "ww-login",
> "options": {
> "appid": "xxxxxx",
> "agentid": "xxxxxx",
> "secret": "xxxxxx",
> "redirectUri":"http://xxxxxxxx/api/plugin/wx/login"
> }
> }
> ]
> }
> 
> ## 什么浏览器
> ~ chrome
> 
> ## 什么系统（Linux, Windows, macOS）
> linux

补充: 调试发现当登陆成功后，cookie中_yapi_token和_yapi_uid 为null
