### ISSUE TITLE
最新版安装后访问出错

### ISSUE THREAD

**Issue by askie** [YMFE/yapi#1829]
## 版本号
1.9.2
## 什么问题
浏览器打开页面，假死，f12查看，是 http://a.com/api/user/status 一直pedding状态，最终出现502错误。

查看日志如下：
2020-06-12T11:51:21.686946483Z log: 服务已启动，请打开下面链接访问: 
2020-06-12T11:51:21.68696696Z http://127.0.0.1:3000/
2020-06-12T11:51:21.75040195Z error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017, mongodb Authentication failed
2020-06-12T11:51:21.750562931Z log: mongodb load success...
2020-06-12T11:51:21.751674798Z (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
2020-06-12T11:51:21.751684386Z     at /api/vendors/exts/yapi-plugin-advanced-mock/server.js:24:38
2020-06-12T11:51:21.751687923Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-06-12T11:51:21.751744609Z (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-06-12T11:51:21.751798419Z (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-06-12T11:51:21.75180421Z (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
2020-06-12T11:51:21.751807406Z     at /api/vendors/exts/yapi-plugin-statistics/server.js:12:38
2020-06-12T11:51:21.751810411Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-06-12T11:51:21.751813457Z (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020-06-12T11:51:21.751873279Z (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
2020-06-12T11:51:21.751881435Z     at /api/vendors/exts/yapi-plugin-wiki/server.js:7:38
2020-06-12T11:51:21.751884851Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-06-12T11:51:21.751887997Z (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2020-06-12T11:52:20.486549469Z (node:1) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

## 如何复现此问题
~ 

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by JiyongWang** [comment]
楼主的问题已经解决了么？解决方案是什么

**Comment by jxhhdx** [comment]
我最新版本(1.13.x)也出现这个问题了
