### ISSUE TITLE
yapi 升级失败

### ISSUE THREAD

**Issue by sendylian** [YMFE/yapi#1876]
## 版本号
~ 1.4.1

## 什么问题
进入到 安装目录下，输入 yapi ls 提示  UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND yapi.demo.qunar.com yapi.demo.qunar.com:80
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
(node:252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
输入 yapi update 提示 getaddrinfo ENOTFOUND yapi.demo.qunar.com yapi.demo.qunar.com:80

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
linux

**Comment by elrichuang** [comment]
我今天想升级也同样遇到这个问题，版本是1.8.6

**Comment by tangcent** [comment]
尝试直接从github拉取?

**Comment by ruyoapp** [comment]
我也是这样，无法升级。查看版本也不行。

**Comment by defp** [comment]
```
bash-4.4# yapi ls 
(node:41) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND yapi.demo.qunar.com yapi.demo.qunar.com:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:41) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
bash-4.4# 
```
