### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by luzhenwei** [YMFE/yapi#1936]
部署日志
当前安装版本： 1.9.2
/usr/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/pool.js:410 if(workItem.socketTimeout) { ^ TypeError: Cannot read property 'socketTimeout' of null at Connection.messageHandler (/usr/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/pool.js:410:17) at Socket.<anonymous> (/usr/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/connection.js:363:20) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readable.push (_stream_readable.js:208:10) at TCP.onread (net.js:601:20)

**Comment by williamcai663** [comment]
我也遇到这个问题，你解决了吗

**Comment by teneous** [comment]
> 我也遇到这个问题，你解决了吗

你是没有启动mongo吧

**Comment by zhcfcl** [comment]
我这里出现这个问题的原因是因为我使用了mysql数据库，没有使用mangodb。
更换为mangodb就可以了。
