### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by TianSuan** [YMFE/yapi#1990]
## 版本号
~ 1.8.5

## 什么问题
~访问yapi异常，服务端抛出错误信息：
(node:1) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

  Error: write ECONNRESET
      at afterWriteDispatched (internal/stream_base_commons.js:146:25)
      at writeGeneric (internal/stream_base_commons.js:137:3)
      at Socket._writeGeneric (net.js:698:11)
      at Socket._write (net.js:710:8)
      at doWrite (_stream_writable.js:417:12)
      at clearBuffer (_stream_writable.js:543:7)
      at Socket.Writable.uncork (_stream_writable.js:321:7)
      at connectionCorkNT (_http_outgoing.js:628:8)
      at processTicksAndRejections (internal/process/task_queues.js:77:11)

## 如何复现此问题
~ 不知道，正常运行了一段时间后今天访问突然不行了，查看日志后发现抛出这个错误

## 什么浏览器
~ Chrome

## 什么系统（Linux, Windows, macOS）
Linux Centos
使用的docker镜像 镜像仓库：registry.cn-hangzhou.aliyuncs.com/anoy/yapi
tag:lasted

**Comment by TianSuan** [comment]
有一个项目配置了每30min同步swagger接口 不知道是不是这个问题导致的

**Comment by TianSuan** [comment]
使用了nginx代理，nginx服务器上磁盘空间没有导致
