### ISSUE TITLE
运行 yapi server 进入部署页面 ，提交部署后报错

### ISSUE THREAD

**Issue by Typeve** [YMFE/yapi#2048]
## 版本号
~  v1.9.2

## 什么问题
~ 运行` yapi server` 进入部署页面 ，提交部署后报错

`Error: getaddrinfo ENOTFOUND yapi.demo.qunar.com`

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
Debian 10

**Comment by zhexing-liu** [comment]
windows 也会报错！click 开始部署   v1.9.2
`internal/modules/cjs/loader.js:883 throw err; ^ Error: Cannot find module 'E:\Program' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }`

![image](https://user-images.githubusercontent.com/68536865/103215740-3677d880-494f-11eb-8353-a9d921a05ad8.png)

**Comment by zhhqiang3** [comment]
加1

**Comment by zhhqiang3** [comment]
yapi.demo.qunar.com 这个域名访问不到 是需要改下配置吗？

**Comment by crazyweeds** [comment]
同样错误让人无力。

**Comment by Yangxiaotian** [comment]
在 Windows 10 下部署同样的报错

**Comment by Eminlin** [comment]
注意数据库是mongoDB  
注意sudo用户的运行  
注意node版本 
然后就部署好了

**Comment by OctopusLian** [comment]
我也碰到这样的问题，是node版本过高导致的吗？

**Comment by thfltt** [comment]
hosts 加上域名解析一般可以解决问题

**Comment by gh316** [comment]
> windows 也会报错！click 开始部署 v1.9.2 `internal/modules/cjs/loader.js:883 throw err; ^ Error: Cannot find module 'E:\Program' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }`
> 
> ![image](https://user-images.githubusercontent.com/68536865/103215740-3677d880-494f-11eb-8353-a9d921a05ad8.png)

大哥，你这错怎么解决的

**Comment by crazyweeds** [comment]
部署都这么费劲，为了一个文档管理，是不是可以绕道选择其他。感谢开源的付出。
