### ISSUE TITLE
部署出现问题，root都没用

### ISSUE THREAD

**Issue by xuzhen97** [YMFE/yapi#211]
## 版本号
~ 

## 什么问题
~部署出现问题？
[root@iZ2ze9sau96dwvpbk2ovgjZ vendors]# npm install
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! syscall spawn
npm ERR! Error: spawn EACCES
npm ERR!     at _errnoException (util.js:1024:11)
npm ERR!     at ChildProcess.spawn (internal/child_process.js:323:11)
npm ERR!     at Object.exports.spawn (child_process.js:502:9)
npm ERR!     at checkGit.then.gitPath (/data/node/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:179:15)
npm ERR!     at tryCatcher (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at Promise._settlePromiseFromHandler (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR!     at Promise._settlePromise (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR!     at Promise._settlePromiseCtx (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR!     at Async._drainQueue (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR!     at Async._drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm ERR!     at Immediate.Async.drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR!     at runCallback (timers.js:789:20)
npm ERR!     at tryOnImmediate (timers.js:751:5)
npm ERR!     at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR!  { Error: spawn EACCES
npm ERR!     at _errnoException (util.js:1024:11)
npm ERR!     at ChildProcess.spawn (internal/child_process.js:323:11)
npm ERR!     at Object.exports.spawn (child_process.js:502:9)
npm ERR!     at checkGit.then.gitPath (/data/node/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:179:15)
npm ERR!     at tryCatcher (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at Promise._settlePromiseFromHandler (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR!     at Promise._settlePromise (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR!     at Promise._settlePromiseCtx (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR!     at Async._drainQueue (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR!     at Async._drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm ERR!     at Immediate.Async.drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR!     at runCallback (timers.js:789:20)
npm ERR!     at tryOnImmediate (timers.js:751:5)
npm ERR!     at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR!   cause: { Error: spawn EACCES
npm ERR!     at _errnoException (util.js:1024:11)
npm ERR!     at ChildProcess.spawn (internal/child_process.js:323:11)
npm ERR!     at Object.exports.spawn (child_process.js:502:9)
npm ERR!     at checkGit.then.gitPath (/data/node/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:179:15)
npm ERR!     at tryCatcher (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at Promise._settlePromiseFromHandler (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR!     at Promise._settlePromise (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR!     at Promise._settlePromiseCtx (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR!     at Async._drainQueue (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR!     at Async._drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm ERR!     at Immediate.Async.drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR!     at runCallback (timers.js:789:20)
npm ERR!     at tryOnImmediate (timers.js:751:5)
npm ERR!     at processImmediate [as _immediateCallback] (timers.js:722:5) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: spawn EACCES\n    at _errnoException (util.js:1024:11)\n    at ChildProcess.spawn (internal/child_process.js:323:11)\n    at Object.exports.spawn (child_process.js:502:9)\n    at checkGit.then.gitPath (/data/node/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:179:15)\n    at tryCatcher (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/data/node/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)',
npm ERR!   code: 'EACCES',
npm ERR!   errno: 'EACCES',
npm ERR!   syscall: 'spawn' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-30T07_50_13_514Z-debug.log

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（linux, window, macox）
linux

**Comment by xuzhen97** [comment]
权限问题，root用户都没法解决sudo -i不好使，应该是安装包时采用的用户不是root，换用户git又没权限，一气之下使用命令`npm install --global yo --allow-root` 解决了问题
