### ISSUE TITLE
二次开发打包错误 ykit pack -m  

### ISSUE THREAD

**Issue by hiover** [YMFE/yapi#2116]
## 版本号
~ 
```$ nvm use 7.6.0  
Now using node v7.6.0 (npm v6.14.8)
$ node -v      
v7.6.0
$ ykit pack -m 
⠙ [Bundler] 4/15 build modulesWarning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
[error] ./client/index.js
Module build failed: /Users/zh/Documents/workspace/qutke/yapi1/vendors/node_modules/_babel-plugin-import@1.13.3@babel-plugin-import/lib/Plugin.js:61
    return {...pluginState.selectedMethods[methodName]};
            ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zh/Documents/workspace/qutke/yapi1/vendors/node_modules/_babel-plugin-import@1.13.3@babel-plugin-import/lib/index.js:2:15)
    at Module._compile (module.js:571:32)
 @ multi index.js

$ ```
## 什么问题
~
![image](https://user-images.githubusercontent.com/21093108/108617246-9f5f6680-744f-11eb-83bd-0151c8b77a0e.png)


## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
macOS

**Comment by zhaoxm2016** [comment]
hi,请问一下如何解决这个问题的哈

**Comment by hiover** [comment]
> hi,请问一下如何解决这个问题的哈
I find solution.
https://github.com/YMFE/yapi/issues/2109
