### ISSUE TITLE
服务启动不起来

### ISSUE THREAD

**Issue by liu826250634** [YMFE/yapi#2193]
## 版本号
~ 

## 什么问题
rookie@rookie-MS-7B53:~/yapi/vendors$ node server/app.js 
/home/rookie/yapi/vendors/exts/yapi-plugin-export-data/controller.js:23
  listToTree = (oldArr) => {
             ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/rookie/yapi/vendors/exts/yapi-plugin-export-data/server.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at extConfig.forEach.plugin (/home/rookie/yapi/vendors/server/plugin.js:265:22)

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
ubuntu18.04

**Comment by snowyfang** [comment]
can't start 
node server/install.js
/my-yapi/vendors/server/utils/db.js:52
  db.then(
     ^

TypeError: Cannot read property 'then' of undefined
    at Object.connect (/Users/sanghongyu/my-yapi/vendors/server/utils/db.js:52:6)
    at Object.<anonymous> (/Users/sanghongyu/my-yapi/vendors/server/install.js:9:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
node v10.24.1
npm v6.14.12
mongoDB v4.4.6
yapi v1.9.2
macOS 10.14.6
