### ISSUE TITLE
服务运行一段时间后就挂了

### ISSUE THREAD

**Issue by cheneyjuu** [YMFE/yapi#2222]
## 版本号
YAPI：1.9.1
NODE：12.22.1

## 什么问题
报错内容：
```
log: 服务已启动，请打开下面链接访问:
http://127.0.0.1:3000/
log: mongodb load success...
(node:22950) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

  Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writevGeneric (internal/stream_base_commons.js:139:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._writev (net.js:794:8)
      at doWrite (_stream_writable.js:401:12)
      at clearBuffer (_stream_writable.js:519:5)
      at Socket.Writable.uncork (_stream_writable.js:338:7)
      at ServerResponse.end (_http_outgoing.js:787:17)
      at respond (/root/ssyuntu-yapi/vendors/node_modules/koa/lib/application.js:222:16)
      at /root/ssyuntu-yapi/vendors/node_modules/koa/lib/application.js:135:26
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## 如何复现此问题
~ 

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
CentOS7

**Comment by liaoqiArno** [comment]
我也有这个 问题，没运行多久就挂了

**Comment by a1105013796** [comment]
v1.9.2同样有

**Comment by TheLittleBoy** [comment]
以前好好的，最近天天晚上宕机，版本1.3.7

**Comment by a1105013796** [comment]
> 以前好好的，最近天天晚上宕机，版本1.3.7

看看是不是被入侵了，最近yapi有个Mock漏洞的，全版本都存在
