### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by longwangsam** [YMFE/yapi#2228]
## 版本号
~ 当前安装版本： 1.9.2

## 什么问题
~
依赖库安装完成，正在初始化数据库mongodb... 后

Error:  /root/my-yapi/vendors/server/utils/commons.js:25
jsf.extend('mock', function () {
    ^

TypeError: jsf.extend is not a function
    at Object.<anonymous> (/root/my-yapi/vendors/server/utils/commons.js:25:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/my-yapi/vendors/server/install.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
Linux CentOS 8.2

**Comment by longwangsam** [comment]
![image](https://user-images.githubusercontent.com/34180723/124276534-83df3780-db76-11eb-90b1-29a16eb84b52.png)

**Comment by wellmatrix** [comment]
问题已经解决，具体方法如下：
https://www.showdoc.com.cn/p/b9c1a4929cee24add87f02b58c40a02f

**Comment by longwangsam** [comment]
> 问题已经解决，具体方法如下：[https](https://www.showdoc.com.cn/p/b9c1a4929cee24add87f02b58c40a02f) ://www.showdoc.com.cn/p/b9c1a4929cee24add87f02b58c40a02f
> [](https://www.showdoc.com.cn/p/b9c1a4929cee24add87f02b58c40a02f)

谢谢
