### ISSUE TITLE
docker 镜像构建问题

### ISSUE THREAD

**Issue by benchem** [YMFE/yapi#2237]
## 版本号
~ 1.9.2

## 什么问题
~ 通过 dockerfile 构建的启动报错

## 如何复现此问题
`
```docker
FROM node:12.18.4-alpine as build
WORKDIR /usr/src/app
COPY package.json package.json
RUN apk add --no-cache --virtual .gyp python3 make g++ \
    && npm config set registry http://repo.iotube.cn/repository/npm-lonntec \
    && npm i --production
COPY . .
EXPOSE 3000
ENTRYPOINT npm start
```
`

错误信息：

> yapi-vendor@1.9.2 start /usr/src/app
>  node server/app.js
/usr/src/app/server/utils/commons.js:26
jsf.extend('mock', function () {
    ^
TypeError: jsf.extend is not a function
    at Object.<anonymous> (/usr/src/app/server/utils/commons.js:26:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/server/app.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yapi-vendor@1.9.2 start: ` node server/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yapi-vendor@1.9.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-06T15_27_09_774Z-debug.log

**Comment by benchem** [comment]
解决办法：
https://www.showdoc.com.cn/p/b9c1a4929cee24add87f02b58c40a02f


![image](https://user-images.githubusercontent.com/15070595/124686287-6d820480-df05-11eb-91ea-9ab2fd7cff2d.png)
