### ISSUE TITLE
commons.js:25 jsf.extend('mock', function () {，TypeError: jsf.extend is not a functio

### ISSUE THREAD

**Issue by wangerbin** [YMFE/yapi#2260]
## 版本号
~ 1.9.1（1.9.2）

## 什么问题
~执行yapi server 到 node server/install.js，就会报错，

## 如何复现此问题
~ node v12.22.2，mongo v4.2.14，npm 6.14.13

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
centos 7.9

**Comment by wangerbin** [comment]
不知道是那个组件或者版本有问题，但是就是过不去

**Comment by zackzhangkai** [comment]
```
部署日志
当前安装版本： 1.9.2
(node:94405) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency (Use `node --trace-warnings ...` to show where the warning was created)
(node:94405) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency (node:94405) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:94405) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
连接数据库成功!
开始下载平台文件压缩包...
http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.9.2.tgz
部署文件完成，正在安装依赖库...
npm
WARN
mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
up to date in 16.306s
16 packages are looking for funding run `npm fund` for details
依赖库安装完成，正在初始化数据库mongodb...
> yapi-vendor@1.9.2 install-server /Users/hugo/my-yapi/vendors > node server/install.js
Error: /Users/hugo/my-yapi/vendors/server/utils/commons.js:25 jsf.extend('mock', function () { ^ TypeError: jsf.extend is not a function at Object.<anonymous> (/Users/hugo/my-yapi/vendors/server/utils/commons.js:25:5) at Module._compile (internal/modules/cjs/loader.js:1068:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) at Module.load (internal/modules/cjs/loader.js:933:32) at Function.Module._load (internal/modules/cjs/loader.js:774:14) at Module.require (internal/modules/cjs/loader.js:957:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/Users/hugo/my-yapi/vendors/server/install.js:3:17) at Module._compile (internal/modules/cjs/loader.js:1068:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) at Module.load (internal/modules/cjs/loader.js:933:32) at Function.Module._load (internal/modules/cjs/loader.js:774:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47
npm
WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
up to date in 12.125s
16 packages are looking for funding run `npm fund` for details
依赖库安装完成，正在初始化数据库mongodb...
> yapi-vendor@1.9.2 install-server /Users/hugo/my-yapi/vendors > node server/install.js
Error: /Users/hugo/my-yapi/vendors/server/utils/commons.js:25 jsf.extend('mock', function () { ^ TypeError: jsf.extend is not a function at Object.<anonymous> (/Users/hugo/my-yapi/vendors/server/utils/commons.js:25:5) at Module._compile (internal/modules/cjs/loader.js:1068:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) at Module.load (internal/modules/cjs/loader.js:933:32) at Function.Module._load (internal/modules/cjs/loader.js:774:14) at Module.require (internal/modules/cjs/loader.js:957:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/Users/hugo/my-yapi/vendors/server/install.js:3:17) at Module._compile (internal/modules/cjs/loader.js:1068:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) at Module.load (internal/modules/cjs/loader.js:933:32) at Function.Module._load (internal/modules/cjs/loader.js:774:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47
```

**Comment by huqiliang** [comment]
> 不知道是那个组件或者版本有问题，但是就是过不去

PR 11天前提交了还没合 应该是不怎么维护了吧

**Comment by icarus910** [comment]
> 用 YApi Pro（ https://github.com/yapi-pro/yapi ）这个分支来部署，已经解决了这个问题。

感谢 前段时间刚被攻击

**Comment by hexiaohei1024** [comment]
> > 不知道是那个组件或者版本有问题，但是就是过不去
> 
> PR 11天前提交了还没合 应该是不怎么维护了吧

我们开了 YApi Pro 来接手维护
用 YApi Pro（ https://github.com/yapi-pro/yapi ）提供的 yapi-pro-cli，即可升级解决。

    npm install -g yapi-pro-cli --registry https://registry.npm.taobao.org
    yapi update
