### ISSUE TITLE
YApi部署报错

### ISSUE THREAD

**Issue by joeyFuck** [YMFE/yapi#2285]
## 版本号

当前node： v14.15.4

npm：6.14.5

mongoDB：5.0.1 Community

## 什么问题

点击部署报错 

```
部署日志
internal/modules/cjs/loader.js:883 throw err; ^ Error: Cannot find module 'C:\Program' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) at Function.Module._load (internal/modules/cjs/loader.js:725:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }
```

**Comment by joeyFuck** [comment]
救救孩子吧

**Comment by chaiyd** [comment]
供参考
- https://github.com/chaiyd/docker/tree/master/yapi
