### ISSUE TITLE
yapi导入swagger中循环的数据时报错

### ISSUE THREAD

**Issue by tuihou123321** [YMFE/yapi#2353]
## 版本号
yapi版本：1.9.2

## 什么问题

yapi从swagger导入数据出现不兼容的情况，循环引用的值无法显示

![image](https://user-images.githubusercontent.com/7146036/133979604-3cd72464-c6bf-4cf8-8ce0-a2784e67f02f.png)

```
{
  "type": "object",
  "properties": {
    "code": {
      "type": "string"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "childList": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/ResourceInfoDTO"
            }
          },
          "have": {
            "type": "boolean"
          },
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "mtime": {
            "type": "string",
            "format": "date-time"
          },
          "operatorId": {
            "type": "integer",
            "format": "int32"
          },
          "operatorName": {
            "type": "string"
          },
          "parentId": {
            "type": "integer",
            "format": "int32"
          },
          "resourceCode": {
            "type": "string"
          },
          "resourceDesc": {
            "type": "string"
          },
          "resourceIcon": {
            "type": "string"
          },
          "resourceName": {
            "type": "string"
          },
          "resourceSort": {
            "type": "integer",
            "format": "int32"
          },
          "resourceType": {
            "type": "string"
          },
          "resourceUrl": {
            "type": "string"
          },
          "status": {
            "type": "integer",
            "format": "int32"
          }
        },
        "title": "ResourceInfoDTO",
        "$$ref": "#/definitions/ResourceInfoDTO"
      }
    },
    "msg": {
      "type": "string"
    },
    "success": {
      "type": "boolean"
    }
  },
  "title": "CommonResponse«List«ResourceInfoDTO»»",
  "$$ref": "#/definitions/CommonResponse«List«ResourceInfoDTO»»"
}

```

报错信息
```
"Error: Prop 'definitions' not found in [type, properties, title, $$ref] (#/definitions/ResourceInfoDTO)\n    at Object.getLocalRef (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:1220:13)\n    at recursiveUtil.resolveSchema (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2771:21)\n    at traverse (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2587:12)\n    at Object.arrayType [as array] (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2052:19)\n    at traverse (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2686:29)\n    at /opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2704:28\n    at Array.forEach (<anonymous>)\n    at traverse (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2702:23)\n    at Object.objectType [as object] (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2388:10)\n    at traverse (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2686:29)\n    at Object.arrayType [as array] (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2052:19)\n    at traverse (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2686:29)\n    at /opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2704:28\n    at Array.forEach (<anonymous>)\n    at traverse (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2702:23)\n    at Object.objectType [as object] (/opt/apps/jushuitan_yapi/vendors/node_modules/json-schema-faker/dist/main.cjs.js:2388:10) in /properties/data/items/0/properties/childList"
```

## 如何复现此问题
把上面的swagger的raw文件导入到yapi中

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
windows

**Comment by ariesly15** [comment]
@tuihou123321 请提供完整的 swagger json 数据

**Comment by hbsjmsjwj** [comment]
这个是我的JSON 使用yapi的转换 也报了这个错误
```javascript
{
    "type":"object",
    "properties":{
        "createUserJobNumber":{
            "type":"string",
            "description":"创建人工号"
        },
        "desc":{
            "type":"string",
            "description":"接口描述"
        },
        "headers":{
            "type":"array",
            "description":"请求头",
            "items":{
                "type":"object",
                "properties":{
                    "desc":{
                        "type":"string",
                        "description":"描述"
                    },
                    "example":{
                        "type":"string",
                        "description":"示例"
                    },
                    "name":{
                        "type":"string",
                        "description":"名称"
                    },
                    "required":{
                        "type":"string",
                        "description":"是否必须"
                    },
                    "value":{
                        "type":"string",
                        "description":"值"
                    }
                },
                "title":"请求头格式",
                "$$ref":"#/definitions/请求头格式"
            }
        },
        "importModel":{
            "type":"string",
            "description":"普通模式/完全覆盖",
            "enum":[
                "NORMAL",
                "FULL_COVERAGE"
            ]
        },
        "method":{
            "type":"string",
            "description":"接口方法"
        },
        "name":{
            "type":"string",
            "description":"接口名称"
        },
        "owner":{
            "type":"string",
            "description":"接口负责人"
        },
        "path":{
            "type":"string",
            "description":"接口路径"
        },
        "request":{
            "type":"object",
            "properties":{
                "location":{
                    "type":"string",
                    "description":"位置",
                    "enum":[
                        "BODY",
                        "QUERY",
                        "PARAMS"
                    ]
                },
                "params":{
                    "type":"array",
                    "description":"参数",
                    "items":{
                        "type":"object",
                        "properties":{
                            "children":{
                                "type":"array",
                                "description":"子节点",
                                "items":{
                                    "originalRef":"JsonSchemaDTO",
                                    "$ref":"#/definitions/JsonSchemaDTO"
                                }
                            },
                            "desc":{
                                "type":"string",
                                "description":"描述"
                            },
                            "example":{
                                "type":"string",
                                "description":"示例"
                            },
                            "name":{
                                "type":"string",
                                "description":"名称"
                            },
                            "required":{
                                "type":"string",
                                "description":"是否必须"
                            },
                            "type":{
                                "type":"string",
                                "description":"类型"
                            }
                        },
                        "title":"JsonSchemaDTO",
                        "$$ref":"#/definitions/JsonSchemaDTO"
                    }
                }
            },
            "title":"参数对象",
            "$$ref":"#/definitions/参数对象"
        },
        "response":{
            "type":"array",
            "description":"响应参数",
            "items":{
                "type":"object",
                "properties":{
                    "desc":{
                        "type":"string",
                        "description":"描述"
                    },
                    "example":{
                        "type":"string",
                        "description":"示例"
                    },
                    "name":{
                        "type":"string",
                        "description":"名称"
                    },
                    "required":{
                        "type":"string",
                        "description":"是否必须"
                    },
                    "type":{
                        "type":"string",
                        "description":"类型"
                    }
                },
                "title":"请求体格式",
                "$$ref":"#/definitions/请求体格式"
            }
        },
        "serverId":{
            "type":"integer",
            "format":"int64",
            "description":"二级服务ID"
        }
    },
    "title":"对外开放的添加接口",
    "$$ref":"#/definitions/对外开放的添加接口"
}
```
