### ISSUE TITLE
升级到最新版本后修改文档时报错

### ISSUE THREAD

**Issue by sunl888** [YMFE/yapi#2371]
## 版本号
1.10.2

## 什么问题
今天升级到最新版本后修改文档时报错。
```
[ 2021/10/19 下午1:57:06 ] [ error ] Cannot read property 'toObject' of null
TypeError: Cannot read property 'toObject' of null
    at projectModel.handleEnvNullData (/yapi/vendors/server/models/project.js:85:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async interfaceController.autoAddTag (/yapi/vendors/server/controllers/interface.js:396:25)
    at async interfaceController.up (/yapi/vendors/server/controllers/interface.js:825:5)
    at async /yapi/vendors/server/utils/commons.js:436:9
    at async module.exports (/yapi/vendors/server/middleware/mockServer.js:152:15)
```

## 如何复现此问题
修改任意接口文档。

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
操作的电脑是Windows，服务器是Linux

**Comment by shencw** [comment]
我的情况是 编辑接口  带tag 保存报错  提示如下

```bash
[ error ] Cannot read property 'toObject' of null
TypeError: Cannot read property 'toObject' of null
    at projectModel.handleEnvNullData (/yapi/vendors/server/models/project.js:85:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async interfaceController.autoAddTag (/yapi/vendors/server/controllers/interface.js:396:25)
    at async interfaceController.up (/yapi/vendors/server/controllers/interface.js:825:5)
    at async /yapi/vendors/server/utils/commons.js:436:9
    at async module.exports (/yapi/vendors/server/middleware/mockServer.js:152:15)
```

解决的方法是：
server/models/project.js:83
修改为
```javascript
handleEnvNullData(data){
    if (data == null) {
      return false;
    }
    data = data.toObject();
    data.toObject = ()=> data;
```
添加了
```javascript
if (data == null) {
      return false;
    }
```

**Comment by vvky** [comment]
> 我的情况是 编辑接口 带tag 保存报错 提示如下
> 
> ```shell
> [ error ] Cannot read property 'toObject' of null
> TypeError: Cannot read property 'toObject' of null
>     at projectModel.handleEnvNullData (/yapi/vendors/server/models/project.js:85:17)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async interfaceController.autoAddTag (/yapi/vendors/server/controllers/interface.js:396:25)
>     at async interfaceController.up (/yapi/vendors/server/controllers/interface.js:825:5)
>     at async /yapi/vendors/server/utils/commons.js:436:9
>     at async module.exports (/yapi/vendors/server/middleware/mockServer.js:152:15)
> ```
> 
> 解决的方法是： server/models/project.js:83 修改为
> 
> ```js
> handleEnvNullData(data){
>     if (data == null) {
>       return false;
>     }
>     data = data.toObject();
>     data.toObject = ()=> data;
> ```
> 
> 添加了
> 
> ```js
> if (data == null) {
>       return false;
>     }
> ```
> 
> 不知道大佬们有没有更好的解决办法~

先生真乃神人也 解决了

**Comment by TuringZhu** [comment]
先生真乃神人也 解决了
