### ISSUE TITLE
内网本地部署报错：Error: Cannot find module 'C:\Program'  

### ISSUE THREAD

**Issue by CaptainLiao** [YMFE/yapi#24]
环境：
*  MongoDB shell version v3.4.10
*  Node v8.9.0
*  npm v5.3.0
已经成功启动可视化部署，配置完成后点击`开始部署`，日志信息如下：
````
module.js:538
 throw err;
 ^
 
 Error: Cannot find module 'C:\Program'
 at Function.Module._resolveFilename (module.js:536:15)
 at Function.Module._load (module.js:466:25)
 at Function.Module.runMain (module.js:676:10)
 at startup (bootstrap_node.js:187:16)
 at bootstrap_node.js:608:3
````
实在找不到原因，求助......

**Comment by suxiaoxin** [comment]
推荐在 mac或linux上试试

**Comment by CaptainLiao** [comment]
我试试

**Comment by suxiaoxin** [comment]
可以加下qq群，有很多人用的window，部署也没问题

**Comment by zheyvsu** [comment]
短名称PROGRA~1？

**Comment by 303182519** [comment]
这个问题最终怎么解决了
