### ISSUE TITLE
保存的时候报错

### ISSUE THREAD

**Issue by chu552415563** [YMFE/yapi#2414]
## 版本号
1.10.2

## 什么问题
从小幺鸡生成json文件，然后导入，基本上所有接口保存的时候都会报错
[ 2021-11-19 9:30:53 ] [ error ] Cannot read property 'toObject' of null                                    
TypeError: Cannot read property 'toObject' of null                                                          
    at projectModel.handleEnvNullData (d:\yapi\my-yapi\vendors\server\models\project.js:85:17)              
    at runMicrotasks (<anonymous>)                                                                          
    at processTicksAndRejections (internal/process/task_queues.js:94:5)                                     
    at async interfaceController.autoAddTag (d:\yapi\my-yapi\vendors\server\controllers\interface.js:396:25)
    at async interfaceController.up (d:\yapi\my-yapi\vendors\server\controllers\interface.js:825:5)         
    at async d:\yapi\my-yapi\vendors\server\utils\commons.js:436:9                                          
    at async module.exports (d:\yapi\my-yapi\vendors\server\middleware\mockServer.js:152:15)  
我试过去修改数据库里接口保存的 请求参数和返回参数，做到和正常保存发出的请求里 参数保存一致，但还是报错，是不是interface表里数据还关联了其他表的数据，缺少了关联数据所以报的错。
## 如何复现此问题
~ 

## 什么浏览器
谷歌浏览器
## 什么系统（Linux, Windows, macOS）
Windows

**Comment by tangcent** [comment]
see #2371
May be fixed by #2374

**Comment by shencw** [comment]
可以试试我的办法，但是感觉这样不是最好的

https://github.com/YMFE/yapi/issues/2371#issuecomment-1046641932

**Comment by RichieSong** [comment]
同样的问题
