### ISSUE TITLE
启动的问题

### ISSUE THREAD

**Issue by john-jun** [YMFE/yapi#2438]
/usr/local/finmaster-yapi/vendors/server/yapi:1
(node:8175) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
     ^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/finmaster-yapi/vendors/server/utils/token.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/finmaster-yapi/vendors/server/controllers/base.js:9:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by Aubreyzhong** [comment]
同样的问题，你找到原因了吗
