### ISSUE TITLE
yapi突发故障，然后无法登录，报504

### ISSUE THREAD

**Issue by boxiaoliao** [YMFE/yapi#2483]
## 版本号
~ 1.8.3镜像

## 什么问题
~登录故障，提示“request failed with status code 504”
运维看日志，发现日志如下：

log: 定时器触发, syncJsonUrl:[http://domain/console/v3/api-docs,合并模式:good](http://domain/console/v3/api-docs,%E5%90%88%E5%B9%B6%E6%A8%A1%E5%BC%8F:good)
log: 获取数据失败http status "502"获取数据失败，请确认 swaggerUrl 是否正确
(node:133) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:133) UnhandledPromiseRejectionWarning: MongoError: Performing an update on the path '_id' would modify the immutable field '_id'
    at Function.create (/home/vendors/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/home/vendors/node_modules/mongoose/node_modules/mongodb/lib/utils.js:149:22)
    at coll.s.topology.update (/home/vendors/node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)
    at /home/vendors/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

图片没法上传，只能这么给日志了。
感觉是同步出了问题，我选择的是只能合并模式，我怀疑是合并的时候出了问题
然后我就一个个去关闭只能合并，到达某个项目的时候，发现"项目的swagger json地址"提示错误。因为涉及到公司数据，我不好把链接发过来，如果有需要，联系我要swagger数据。

## 如何复现此问题
~ 不固定，某个时刻忽然触发后，就没法登录了。

## 什么浏览器
~ chrome

## 什么系统（Linux, Windows, macOS）
windows10

**Comment by boxiaoliao** [comment]
chrome 版本 97.0.4692.99（正式版本） （64 位
