### ISSUE TITLE
api/open/import_data接口导入数据服务错误，40011

### ISSUE THREAD

**Issue by rendchao** [YMFE/yapi#2520]
## 版本号
~ [1.5.11]

## 什么问题
~api/open/import_data接口导入数据，返回
{
    "errcode": 40011,
    "errmsg": "服务器出错...",
    "data": null
}

## 如何复现此问题
~ postman请求 http://域名/api/open/import_data

## 什么浏览器
~  Chrome

## 什么系统（Linux, Windows, macOS）
Linux

## 报错详情信息
<html>
<body>

for await (const chunk of (0, blobHelpers_1.consumeBlobParts)(__classPrivateFieldGet(this, _Blob_parts, "f"))) {
--
Thu, Mar 24 2022 11:14:58 am | ^^^^^
Thu, Mar 24 2022 11:14:58 am |  
Thu, Mar 24 2022 11:14:58 am | SyntaxError: Unexpected reserved word
Thu, Mar 24 2022 11:14:58 am | at createScript (vm.js:80:10)
Thu, Mar 24 2022 11:14:58 am | at Object.runInThisContext (vm.js:139:10)
Thu, Mar 24 2022 11:14:58 am | at Module._compile (module.js:617:28)
Thu, Mar 24 2022 11:14:58 am | at Object.Module._extensions..js (module.js:664:10)
Thu, Mar 24 2022 11:14:58 am | at Module.load (module.js:566:32)
Thu, Mar 24 2022 11:14:58 am | at tryModuleLoad (module.js:506:12)
Thu, Mar 24 2022 11:14:58 am | at Function.Module._load (module.js:498:3)
Thu, Mar 24 2022 11:14:58 am | at Module.require (module.js:597:17)
Thu, Mar 24 2022 11:14:58 am | at require (internal/module.js:11:18)
Thu, Mar 24 2022 11:14:58 am | at Object.<anonymous> (/vendors/node_modules/formdata-node/lib/cjs/File.js:16:16)
Thu, Mar 24 2022 11:14:58 am | at Module._compile (module.js:653:30)
Thu, Mar 24 2022 11:14:58 am | at Object.Module._extensions..js (module.js:664:10)
Thu, Mar 24 2022 11:14:58 am | at Module.load (module.js:566:32)
Thu, Mar 24 2022 11:14:58 am | at tryModuleLoad (module.js:506:12)
Thu, Mar 24 2022 11:14:58 am | at Function.Module._load (module.js:498:3)
Thu, Mar 24 2022 11:14:58 am | at Module.require (module.js:597:17)
Thu, Mar 24 2022 11:14:58 am | error: TypeError: Cannot read property 'length' of undefined
Thu, Mar 24 2022 11:14:58 am | at handleAddInterface (/vendors/common/HandleImportData.js:61:19)
Thu, Mar 24 2022 11:14:58 am | at <anonymous>
Thu, Mar 24 2022 11:14:58 am | at process._tickCallback (internal/process/next_tick.js:189:7)

</body>
</html>

![image](https://user-images.githubusercontent.com/55875203/159836697-33a1fc6b-8717-4452-bb71-55c389b65834.png)

**Comment by pathing** [comment]
+1, 请问有解决了么

**Comment by onecer** [comment]
same problem on 1.10.2
