### ISSUE TITLE
master 分支安装错误

### ISSUE THREAD

**Issue by mogudy** [YMFE/yapi#2563]
## 版本号
~ latest

## 什么问题
~ 无论是 docker 打包，还是宿主机直接编译，都有问题，详情附后

## 如何复现此问题
~ 详情附后

## 什么浏览器
~ 安装错误，还没到浏览器

## 什么系统（Linux, Windows, macOS）
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

Node Version: v16.13.2
NPM Version: 8.1.2

【 ubuntu 下不修改 node-sass 版本号，npm i 即出错】
1. 执行步骤
```
git clone https://github.com/YMFE/yapi.git vendors
rm vendors/package-lock.json
cd vendors
npm i -f --omit-env=dev --registry=https://registry.npmmirror.com
```
2. 异常说明
```
npm ERR! code 1
npm ERR! path /root/yapi/test/vendors/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /root/yapi/test/vendors/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! make: Entering directory '/root/yapi/test/vendors/node_modules/node-sass/build'
```

【 ubuntu 下修改 node-sass 版本号，npm i 成功， ykit pack 失败】
1. 执行步骤：
```
git clone https://github.com/YMFE/yapi.git vendors
rm vendors/package-lock.json
sed -i 's|"node-sass": "^4.9.0",|"node-sass": "^7.0.1",|g' vendors/package.json
cd vendors
npm i -f --omit-env=dev --registry=https://registry.npmmirror.com
ykit pack -m
```
2. 异常说明：
```
[error] ./client/styles/common.scss
Module build failed: Error: Node Sass version 7.0.1 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/root/yapi/test/vendors/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/root/yapi/test/vendors/node_modules/sass-loader/dist/index.js:79:18)
 @ ./client/index.js 7:0-31

/root/yapi/test/vendors/client/components/MyPopConfirm/MyPopConfirm.js
  29:3  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

/root/yapi/test/vendors/client/components/AuthenticatedComponent.js
  28:5  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  31:5  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
```

【 在 docker 中，使用 node-10 环境（与 node-sass 4.10 适配），npm i 成功， ykit pack 失败】
1. docker 文件
```
FROM node:10.24.1-slim

RUN sed -i -e 's|deb.debian.org/debian|mirrors.aliyun.com/debian|g' -e 's|security.debian.org/debian-security|mirrors.aliyun.com/debian-security|g' /etc/apt/sources.list
RUN apt update && apt install make gcc python g++ git -y
RUN cd /root && git clone https://github.com/YMFE/yapi.git vendors
RUN cd /root/vendors && rm package-lock.json && npm i --force --production --registry=https://registry.npmmirror.com
RUN npm i -g ykit yapi-cli --registry=https://registry.npmmirror.com
RUN cd /root/vendors && npm i -f compression-webpack-plugin assets-webpack-plugin --registry=https://registry.npmmirror.com

WORKDIR /root
COPY plugins/ /root/vendors/node_modules/
COPY config.json /root/config.json
COPY ykit.config.js /root/vendors/ykit.config.js
RUN cd /root/vendors && ykit pack -m

ENV TZ="Asia/Shanghai"
COPY entrypoint.sh /usr/local/bin/
EXPOSE 3000
ENTRYPOINT ["entrypoint.sh"]
```

2. 异常说明
```
[error] ./client/components/AuthenticatedComponent.js

/root/vendors/client/components/AuthenticatedComponent.js
  28:5  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  31:5  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

```

**Comment by mogudy** [comment]
已解决。
使用 node-10
swagger-client 固定版本为 3.5.1
eslint-plugin-react 固定版本为 7.1.0

**Comment by zgh1121** [comment]
123123
