### ISSUE TITLE
Cannot find module '/api/vendors/server/app.js'

### ISSUE THREAD

**Issue by mayan404** [YMFE/yapi#2694]
## 版本号
~ 
1.83
## 什么问题
~
这个yapi 的docker 是很早之前运行在服务器中的，突然就无法访问了，现在启动 yapi 的时候报如下错误。

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/api/vendors/server/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

## 如何复现此问题
~ 
启动 yapi 时报错

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
linux

**Comment by xwj-vic** [comment]
所有问题看这里就可以解决了，折腾了好久总结出来的：https://blog.opendeveloper.cn/yapi
