### ISSUE TITLE
MongoError: server instance pool was destroyed

### ISSUE THREAD

**Issue by sonce** [YMFE/yapi#2712]
## 版本号
[版本: 1.11.0](https://github.com/YMFE/yapi/blob/master/CHANGELOG.md)

## 什么问题
error: MongoError: server instance pool was destroyed
    at basicWriteValidations (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:388:12)
    at basicReadValidations (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:395:17)
    at Server.command (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:217:19)
    at checkServer (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/monitoring.js:144:12)
    at /yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/monitoring.js:197:7
    at /yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:788:9
    at eachAsync (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/utils.js:135:5)
    at Pool.reset (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:765:3)
    at /yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/monitoring.js:195:19
    at /yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/monitoring.js:160:18
    at Server.command (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:219:14)
    at checkServer (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/monitoring.js:144:12)
    at Object.monitorServer [as monitorFunction] (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/monitoring.js:186:3)
    at Server.monitor (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:196:12)
    at Timeout._onTimeout (/yapi/vendors/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:827:22)
    at listOnTimeout (internal/timers.js:549:17) {
  [Symbol(mongoErrorContextSymbol)]: {}
}

## 如何复现此问题
时不时出现

## 什么系统（Linux, Windows, macOS）
Linux

**Comment by yyltesting** [comment]
你看看你的mongodb服务是不是停了
