### ISSUE TITLE
访问系统信息页面服务端奔溃

### ISSUE THREAD

**Issue by NHZEX** [YMFE/yapi#275]
## 版本号
v1.3.11

## 什么问题
访问系统信息页面服务端发生奔溃

## 如何复现此问题
访问 http://localhost:3000/statistic

## 什么浏览器
Chrome

## 什么系统（Linux, Windows, macOS）
CentOS Linux release 7.4.1708 (Core)
node v9.10.1

## 奔溃信息
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1345:14)
    at listenInCluster (net.js:1386:12)
    at Server.listen (net.js:1474:7)
    at Application.listen (/root/my-yapi/vendors/node_modules/koa/lib/application.js:65:26)
    at Application.app.listen (/root/my-yapi/vendors/node_modules/koa-websocket/index.js:45:28)
    at Object.<anonymous> (/root/my-yapi/vendors/server/app.js:59:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
Emitted 'error' event at:
    at Server.WebSocketServer._ultron.on (/root/my-yapi/vendors/node_modules/ws/lib/WebSocketServer.js:85:46)
    at Server.emit (events.js:180:13)
    at emitErrorNT (net.js:1365:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by NHZEX** [comment]
更新到1.3.12 不会发生奔溃了。

**Comment by wong2843** [comment]
可以看看这个 https://github.com/YMFE/yapi/issues/288
