### ISSUE TITLE
无法启动开发服务器

### ISSUE THREAD

**Issue by mhcgrq** [YMFE/yapi#288]
## 版本号
~ 1.3.12

## 什么问题
~ 使用 `npm run dev` 时报错
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Application.listen (/Users/downpooooour/Documents/kjl/yapi/vendors/node_modules/koa/lib/application.js:65:26)
    at Object.<anonymous> (/Users/downpooooour/Documents/kjl/yapi/vendors/server/app.js:59:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

## 如何复现此问题
~ `npm run dev` ，换了好几个端口也没用

## 什么浏览器
~ N/A

## 什么系统（Linux, Windows, macOS）
macOS，Node8.9.1，2015 mbp

**Comment by gaoxiaomumu** [comment]
你看一下3000接口是不是被占用了

**Comment by mhcgrq** [comment]
最后发现换到3011或者8000就可以。
同时发现`ykit.config.js`中的 loader 不全，无法打包图片文件，建议加上
```
        baseConfig.module.preLoaders.push({
          test: /\.(gif|jpg|jpeg|png|woff|woff2|eot|ttf|svg)(\?v=.+)?$/,
          loader: 'url-loader',
          options: {
              limit: 20480,
              name: '[path][name].[ext]?[sha256:hash:base64:8]'
          }
        });
```

**Comment by wong2843** [comment]
@mhcgrq 安装你说的是能解决，请问大佬出现这个问题的原因是啥？
