### ISSUE TITLE
用yapi-cli安装时，出问题

### ISSUE THREAD

**Issue by golden-hu** [YMFE/yapi#398]
## 版本号
~ 

## 什么问题
在yapi server 之后提示，通过IP访问
在通过IP访问的时候在控制台输出：
 UnhandledPromiseRejectionWarning: Error: Request failed with status code 502
    at createError (/usr/lib/node_modules/yapi-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/yapi-cli/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/yapi-cli/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
(node:4697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## 如何复现此问题
根据CentOS配置指引+安装说明，都是默认安装，然后通过远程访问

## 什么浏览器
firefox

## 什么系统（Linux, Windows, macOS）
客户端Mac 服务器，CentOS7

**Comment by gaoxiaomumu** [comment]
如果 你是 yapi  server 时出错的话是因为我们的服务器刚才出了问题，现在应该没有关系了

**Comment by anming-john** [comment]
我现在也出现这个问题， 是你们服务不稳定吗， 还是什么原因， 
`(node:26664) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 120.27.128.131:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:26664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)`‘
yapi server 能启动， 在浏览器上范围地址时就报这个错
