### ISSUE TITLE
后台错误日志

### ISSUE THREAD

**Issue by alangong114** [YMFE/yapi#401]
## 版本号
1.3.17版本
centos 7 
node v9.8.0
chrome
## 什么问题
(node:10208) UnhandledPromiseRejectionWarning: MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/root/my-yapi/vendors/node_modules/mongodb-core/lib/error.js:31:11)
    at /root/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/root/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/root/my-yapi/vendors/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/root/my-yapi/vendors/node_modules/mongodb-core/lib/connection/connection.js:309:22)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)
(node:10208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

## 如何复现此问题
点击右上角头像,系统信息时，后台报错

**Comment by gaoxiaomumu** [comment]
mongodb3.6  版本降到 3.4 就好了
