### ISSUE TITLE
【求助】本地构建报错，像是less-loader未生效

### ISSUE THREAD

**Issue by czonechan** [YMFE/yapi#504]
## 版本号
yapi v1.3.22
node v8.9.0

## 什么问题
本地构建报错
NODE_ENV=production ykit pack -m

[ykit] ykit@2.2.1
[error] ./client/styles/theme.less
Module build failed: ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
|
| @ant-prefix             : ant;
    at doBuild (/Users/zj-db0909/.nvm/versions/node/v8.9.0/lib/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:303:19)
    at runLoaders (/Users/zj-db0909/.nvm/versions/node/v8.9.0/lib/node_modules/ykit/node_modules/webpack/lib/NormalModule.js:209:11)
    at /Users/zj-db0909/.nvm/versions/node/v8.9.0/lib/node_modules/ykit/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/zj-db0909/.nvm/versions/node/v8.9.0/lib/node_modules/ykit/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at /Users/zj-db0909/.nvm/versions/node/v8.9.0/lib/node_modules/ykit/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /Users/zj-db0909/.nvm/versions/node/v8.9.0/lib/node_modules/ykit/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./client/styles/theme.less
 @ ./client/index.js
 @ multi ./index.js

[error] ./client/styles/theme.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~antd/dist/antd.less';
|
| @ant-prefix             : ant;
 @ ./client/styles/theme.less 4:14-39
 @ ./client/index.js
 @ multi ./index.js

## 如何复现此问题
~ 

## 什么浏览器
~

**Comment by gaoxiaomumu** [comment]
本地构建的意思是二次开发吗？
