### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by freestyledash** [YMFE/yapi#524]
## 系统（macOS）
使用命令：
npm install -g yapi-cli --registry https://registry.npm.taobao.org
yapi server

安装出错
/usr/local/lib/node_modules/yapi-cli/src/commands/import.js:16
  run: async function (argv) {
             ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/yapi-cli/src/index.js:10:23
    at Array.forEach (native)

**Comment by gaoxiaomumu** [comment]
![image](https://user-images.githubusercontent.com/21135585/44987141-b4fb2000-afb8-11e8-8b1d-0ffbef1d26d8.png)
应该是node的版本问题
