### ISSUE TITLE
执行yapi server异常

### ISSUE THREAD

**Issue by yue530tom** [YMFE/yapi#670]
## 版本号
1.4
## 什么问题
yapi server异常
## 如何复现此问题

[root@server119-ke yapi]# npm install -g yapi-cli --registry https://registry.npm.taobao.org
/usr/bin/yapi -> /usr/lib/node_modules/yapi-cli/bin/yapi-cli
/usr/bin/yapi-cli -> /usr/lib/node_modules/yapi-cli/bin/yapi-cli
/usr/lib
└── yapi-cli@1.2.8 

[root@server119-ke yapi]# yapi server
/usr/lib/node_modules/yapi-cli/src/commands/import.js:16
  run: async function (argv) {
             ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/yapi-cli/src/index.js:10:23
[root@server119-ke yapi]#
## 什么浏览器
无
## 什么系统（Linux, Windows, macOS）
centos7

**Comment by yue530tom** [comment]
卸载nojs8 清理环境，重新安装nodejs8  解决问题，关闭issue
