### ISSUE TITLE
登陆界面无法对接LDAP

### ISSUE THREAD

**Issue by jackchu123** [YMFE/yapi#676]
## 版本号
~ 1.4.1

## 什么问题
~ 对接LDAP，出现如下错误
```
(node:73) UnhandledPromiseRejectionWarning: Error:  ubuntu has unbalanced parentheses
    at matchParens (/my-yapi/vendors/node_modules/ldap-filter/lib/index.js:49:11)
    at _buildFilterTree (/my-yapi/vendors/node_modules/ldap-filter/lib/index.js:155:18)
    at _parseString (/my-yapi/vendors/node_modules/ldap-filter/lib/index.js:411:17)
    at Object.parse (/my-yapi/vendors/node_modules/ldap-filter/lib/index.js:422:12)
    at Object.parseString (/my-yapi/vendors/node_modules/ldapjs/lib/filters/index.js:176:25)
    at Client.search (/my-yapi/vendors/node_modules/ldapjs/lib/client/client.js:769:30)
    at Promise.then (/my-yapi/vendors/server/utils/ldap.js:131:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:73) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
操作如下：
1.yapi是通过docker启动，其它功能正常，可以手动添加账户
2.ldap服务正常，我安装apache对接ldap，可以直接输入ubuntu账户登陆，且ldap查看有ubuntu 用户
3.如上错误是nohup.out文件得到
配置文件如下:
```
"ldapLogin": {
      "enable": true,
      "server": "ldap://IP",
      "baseDn": "CN=admin,DC=server,DC=world",
      "bindPassword": "xxx",
      "searchDn": "OU=people,DC=server,DC=com",
      "searchStandard": "&(objectClass=*)",
      "emailPostfix": "@xxx.cn",
      "emailKey": "mail",
      "usernameKey": "name"
   }
```
## 如何复现此问题
~ 

## 什么浏览器
~ google浏览器

## 什么系统（Linux, Windows, macOS）
ldap与apache软件系统为ubuntu14.04 LTS
yapi 使用Docker version 17.03.2-ce   image latest

谢谢

**Comment by guxianxiong** [comment]
问题有解决吗？我也碰到同样的问题

**Comment by zhongkouwei** [comment]
请问有解决吗，

**Comment by iDube** [comment]
同样的问题

**Comment by W-BC0001** [comment]
**问题已解决**

> 主要还是 searchStandard 配置项的问题, 多试几次就好了~

LDAP正确配置(注意替换里面的条件)

```shell
      "searchStandard": "&(gidNumber=100000)(uid=%s)",
      "usernameKey": "cn"
```

LDAP错误配置

```shell
      "searchStandard": "(&(objectClass=*)(uid=%(user)s)(!(gidNumber=000000)))",
      "usernameKey": "cn"
```
