### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by stavid** [YMFE/yapi#689]
## 版本号
~ 1.4.1

## 什么问题
~
部署异常

/usr/local/node/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/pool.js:411 if(workItem.socketTimeout) { ^ TypeError: Cannot read property 'socketTimeout' of null at Connection.messageHandler (/usr/local/node/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/pool.js:411:17) at Socket.<anonymous> (/usr/local/node/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/connection.js:363:20) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readable.push (_stream_readable.js:208:10) at TCP.onread (net.js:594:20)

## 如何复现此问题
~ 

## 什么浏览器
~ 

## 什么系统（Linux, Windows, macOS）
linux

**Comment by Tyebile** [comment]
+1
