### ISSUE TITLE
部署不成功，换了几种方式都不行

### ISSUE THREAD

**Issue by mxinran** [YMFE/yapi#690]
## 版本号
~ 1.4.1

## 什么问题
~Error:  internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'json-schema-faker'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/data/api/yapi/my-yapi/vendors/server/utils/commons.js:19:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/data/api/yapi/my-yapi/vendors/server/install.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

## 如何复现此问题
~ centos7安装部署

## 什么浏览器
~ 火狐

## 什么系统（Linux, Windows, macOS）
centos7

**Comment by 18300621454** [comment]
同样的报错，版本：v1.3.23  系统：centos7  谷歌浏览器

**Comment by 18300621454** [comment]
Yapi的QQ群，下载文档里面有解决办法。要用源码安装node-v8.11.1.tar.gz的版本，你可以去看看。
