### ISSUE TITLE
mongodb 修改配置在什么地方

### ISSUE THREAD

**Issue by skyyan2000** [YMFE/yapi#787]
安装报错 其相关日志如下

当前安装版本： 1.4.4
/data/software/node/node-v8.0.0-linux-x64/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/pool.js:410 if(workItem.socketTimeout) { ^ TypeError: Cannot read property 'socketTimeout' of null at Connection.messageHandler (/data/software/node/node-v8.0.0-linux-x64/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/pool.js:410:16) at Socket.<anonymous> (/data/software/node/node-v8.0.0-linux-x64/lib/node_modules/yapi-cli/node_modules/mongodb-core/lib/connection/connection.js:363:20) at emitOne (events.js:115:13) at Socket.emit (events.js:210:7) at addChunk (_stream_readable.js:250:12) at readableAddChunk (_stream_readable.js:237:11) at Socket.Readable.push (_stream_readable.js:195:10) at TCP.onread (net.js:586:20)

**Comment by Walle-w** [comment]
你yum装的在/etc/mongo.conf
包安装的就在你自己解压的目录下啊

**Comment by FantasyLeo** [comment]
mongo的问题不应该在这里提问。。。 这种问题也没有关闭。这项目维护人员有点少。。。
