### ISSUE TITLE
yapi-cli 1.4.0报错（部署时yapi server 和 升级时yapi ls报同样错误）

### ISSUE THREAD

**Issue by dreamsqin** [YMFE/yapi#814]
## 版本号
~ Yapi-cli   @@1.4.0

## 什么问题
~原本部署的yapi为1.3.23版本，现想升级为1.4.4版本，cd进入到项目目录后，执行yapi ls报错：

## 如何复现此问题
~ 升级Yapi-cli至1.4.0版本，以下两种方式均报相同错误：
1、cd进入原本部署的1.3.23版本的yapi项目目录，执行yapi ls，命令行报错：

(node:1160) UnhandledPromiseRejectionWarning: Error: unable to get local issuer
certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
(node:1160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:1160) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit  @code.

2、由于升级不成功，所以想重新部署，执行yapi server，此时正常，但进入浏览器后，页面显示空白，命令行报错：

在浏览器打开 http://0.0.0.0:9090 访问。非本地服务器，请将 0.0.0.0 替换成指定的域
名或ip
(node:8372) UnhandledPromiseRejectionWarning: Error: unable to get local issuer
certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
(node:8372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:8372) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
(node:8372) UnhandledPromiseRejectionWarning: Error: unable to get local issuer
certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
(node:8372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 4)

## 什么浏览器
~ Chrome 71.0.3578.98

## 什么系统（Linux, Windows, macOS）
Windows 7

**Comment by supperdsj** [comment]
same
