### ISSUE TITLE
可以在md里面增加开发环境搭建步骤么,这边开发环境搭建不起来

### ISSUE THREAD

**Issue by gukun00** [YMFE/yapi#86]
可以在md里面增加开发环境搭建步骤么,这边开发环境搭建不起来,谢谢.

**Comment by gukun00** [comment]
安装完ykit,npm install之后,在项目根目录下运行npm run dev,会出现错误.
```
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/gukun/Git/yapi/server/**/* /Users/gukun/Git/yapi/common/**/* plugins /Users/gukun/Git/yapi/exts/**/*
[nodemon] starting `node server/app.js dev`
module.js:515
    throw err;
    ^

Error: Cannot find module '../../config.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/gukun/Git/yapi/server/yapi.js:4:16)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
[nodemon] app crashed - waiting for file changes before starting...
module.js:515
    throw err;
    ^

Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at initPlugins (/Users/gukun/Git/yapi/ykit.config.js:28:18)
    at Object.<anonymous> (/Users/gukun/Git/yapi/ykit.config.js:55:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```
### 如果在外面建报错中提示的config文件,后面做下去依然会有问题,所以请各位大大帮忙写个说明,多谢了.

**Comment by suxiaoxin** [comment]
看下文档 插件开发-二次开发
