### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by pencilso** [YMFE/yapi#912]
## 版本号
~ 最新版1.5.7
## windows

错误信息如下（看不懂）：
```
当前安装版本： 1.5.7
连接数据库成功!
开始下载平台文件压缩包...
http://registry.npm.taobao.org/yapi-vendor/download/yapi-vendor-1.5.7.tgz
部署文件完成，正在安装依赖库...
npm
WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated
babel-preset-es2015@6.24.1: ???? Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
npm WARN deprecated babel-preset-es2017@6.24.1: ???? Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated ejs@2.3.4: Critical security bugs fixed in 2.5.5
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm
WARN deprecated topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm
WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.
> dtrace-provider@0.8.7 install /usr/local/centos_x64/yapi/vendors/node_modules/dtrace-provider > node-gyp rebuild || node suppress-error.js
gyp
WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/centos_x64/yapi/vendors/node_modules/dtrace-provider/.node-gyp"
gyp
WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/centos_x64/yapi/vendors/node_modules/dtrace-provider/.node-gyp'
gyp ERR! System Linux 3.10.0-862.el7.x86_64
gyp
ERR! command "/usr/local/centos_x64/node-v10/bin/node" "/usr/local/centos_x64/node-v10/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /usr/local/centos_x64/yapi/vendors/node_modules/dtrace-provider gyp
ERR! node -v v10.15.3 gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
> jsonpath@1.0.1 postinstall /usr/local/centos_x64/yapi/vendors/node_modules/jsonpath > node lib/aesprim.js > generated/aesprim-browser.js
sh: generated/aesprim-browser.js: Permission denied
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.1.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself. npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself. npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself. npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself. npm WARN yapi-vendor@1.5.7 license should be a valid SPDX license expression
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonpath@1.0.1 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js` npm ERR! Exit status 1
npm ERR! npm ERR!
Failed at the jsonpath@1.0.1 postinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2019-03-25T03_53_48_548Z-debug.log
依赖库安装完成，正在初始化数据库mongodb...
> yapi-vendor@1.5.7 install-server /usr/local/centos_x64/yapi/vendors > node server/install.js
Error: internal/modules/cjs/loader.js:584 throw err; ^ Error: Cannot find module 'json-schema-faker' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15) at Function.Module._load (internal/modules/cjs/loader.js:508:25) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:22:18) at Object.<anonymous> (/usr/local/centos_x64/yapi/vendors/server/utils/commons.js:21:13) at Module._compile (internal/modules/cjs/loader.js:701:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) at Module.load (internal/modules/cjs/loader.js:600:32) at tryModuleLoad (internal/modules/cjs/loader.js:539:12) at Function.Module._load (internal/modules/cjs/loader.js:531:3) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:22:18) at Object.<anonymous> (/usr/local/centos_x64/yapi/vendors/server/install.js:3:17) at Module._compile (internal/modules/cjs/loader.js:701:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) at Module.load (internal/modules/cjs/loader.js:600:32) 
```

**Comment by pencilso** [comment]
问题已经解决，解决方案：用源码编译nodejs，再安装nodejs
